import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
const sidebars: SidebarsConfig = {
  notes: [
    {
      type: "autogenerated",
      dirName: "notes",
    },
  ],
  // projects: [
  //   {
  //     type: 'autogenerated',
  //     dirName: 'projects',
  //   },
  // ],
};
export default sidebars;
